# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 609c8d8872e8330aeaf412e7f0767fd3e3bebe89601b681667210e6ea22f88320e4a3dd889192268f1fe6e827c9fc04273e19c657f8ddd04503a159cc71266d9

test:
  secret_key_base: fd73ea450196add730b36151d1dac0d36bbbd0e4f31273bbe6a38519cc2cae3095baf26a49ae8027e7df09b93c28f8ad9fa3928ed5d30f4c6e85dd29cfeba84e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
